/** @typedef {'PREP'|'SERVICE'|'CLOSING'} DayPhase */

export const CONFIG = {
  CANVAS_W: 960,
  CANVAS_H: 640,
  TILE: 32,
  PLAYER_SPEED: 175,
  PLAYER_SIZE: 76,
  CUSTOMER_SPEED: 58,
  INTERACT_RANGE: 72,
  CLICK_ARRIVE_DIST: 10,
  /** Mouse/touch follow ignores the pointer until it leaves this radius (fine clicks). */
  FOLLOW_DEAD_ZONE: 58,
  /** Max finger travel (logical px) that still counts as a tap / action, not a drag. */
  TAP_SLOP: 16,
  /** Soft day length in seconds (~5 minutes). No forced rush. */
  DAY_LENGTH: 300,
  /** Base wait patience before leaving (~3.5 minutes). */
  CUSTOMER_PATIENCE: 210,
  /** Ticket crawl speed on conveyor (slow). */
  TICKET_SPEED: 28,
  OVERVIEW_SECONDS: 5,
};

export const PHASES = /** @type {DayPhase[]} */ (['PREP', 'SERVICE', 'CLOSING']);

/** Day difficulty: how many customers can be active + spawn spacing. */
export function daySettings(day) {
  const d = Math.max(1, day);
  if (d <= 2) {
    return {
      maxCustomers: 1,
      spawnInterval: d === 1 ? 70 : 55,
      oneAtATime: true,
      easyPool: true,
    };
  }
  return {
    maxCustomers: Math.min(2 + Math.floor((d - 3) / 2), 4),
    spawnInterval: Math.max(28, 55 - d * 4),
    oneAtATime: false,
    easyPool: false,
  };
}

/** Brighter cozy bakery palette */
export const COLORS = {
  dining: '#ffd6a3',
  kitchen: '#ffe8b8',
  pos: '#ffc98a',
  office: '#f0c8a0',
  bathroom: '#b8e4f0',
  wall: '#8b4d2b',
  wallTop: '#5c3018',
  floorLine: 'rgba(180, 90, 40, 0.12)',
  conveyor: '#7a8a9a',
  conveyorBelt: '#5a6a7a',
  ink: '#2b2118',
  cream: '#fff6e0',
  butter: '#ffc94a',
  berry: '#e85d75',
  mint: '#5fd39a',
  highlight: '#ffe066',
  destination: 'rgba(95, 211, 154, 0.55)',
  sky: '#ffe9c8',
};

/**
 * Image keys scanned from assets/characters/ and assets/furniture/.
 * Missing files soft-fail in AssetLoader (sit poses / red_panda may arrive later).
 * Direction keys: {id}_front|_back|_side|_left
 * Sit poses: {id}_sit → assets/characters/poses/{id}_sit.png
 * Furniture kinds map to oven, display, register, table, sink, etc.
 */
export const ASSET_MANIFEST = {
  images: {
    bear: 'assets/characters/current/bear.png',
    bear_back: 'assets/characters/directions/bear_back.png',
    bear_front: 'assets/characters/directions/bear_front.png',
    bear_glasses: 'assets/characters/current/bear_glasses.png',
    bear_glasses_back: 'assets/characters/directions/bear_glasses_back.png',
    bear_glasses_front: 'assets/characters/directions/bear_glasses_front.png',
    bear_glasses_left: 'assets/characters/directions/bear_glasses_left.png',
    bear_glasses_side: 'assets/characters/directions/bear_glasses_side.png',
    bear_hat: 'assets/characters/current/bear_hat.png',
    bear_hat_back: 'assets/characters/directions/bear_hat_back.png',
    bear_hat_front: 'assets/characters/directions/bear_hat_front.png',
    bear_hat_glasses: 'assets/characters/current/bear_hat_glasses.png',
    bear_hat_glasses_back: 'assets/characters/directions/bear_hat_glasses_back.png',
    bear_hat_glasses_front: 'assets/characters/directions/bear_hat_glasses_front.png',
    bear_hat_glasses_left: 'assets/characters/directions/bear_hat_glasses_left.png',
    bear_hat_glasses_side: 'assets/characters/directions/bear_hat_glasses_side.png',
    bear_hat_left: 'assets/characters/directions/bear_hat_left.png',
    bear_hat_side: 'assets/characters/directions/bear_hat_side.png',
    bear_left: 'assets/characters/directions/bear_left.png',
    bear_side: 'assets/characters/directions/bear_side.png',
    bookcase: 'assets/furniture/bookcase.png',
    bunny: 'assets/characters/current/bunny.png',
    bunny_back: 'assets/characters/directions/bunny_back.png',
    bunny_front: 'assets/characters/directions/bunny_front.png',
    bunny_left: 'assets/characters/directions/bunny_left.png',
    bunny_side: 'assets/characters/directions/bunny_side.png',
    capybara: 'assets/characters/current/capybara.png',
    capybara_back: 'assets/characters/directions/capybara_back.png',
    capybara_front: 'assets/characters/directions/capybara_front.png',
    capybara_left: 'assets/characters/directions/capybara_left.png',
    capybara_side: 'assets/characters/directions/capybara_side.png',
    citrusTree: 'assets/furniture/citrus_tree.png',
    crocodile: 'assets/characters/current/crocodile.png',
    crocodile_back: 'assets/characters/directions/crocodile_back.png',
    crocodile_front: 'assets/characters/directions/crocodile_front.png',
    crocodile_left: 'assets/characters/directions/crocodile_left.png',
    crocodile_side: 'assets/characters/directions/crocodile_side.png',
    deer: 'assets/characters/current/deer.png',
    deer_back: 'assets/characters/directions/deer_back.png',
    deer_front: 'assets/characters/directions/deer_front.png',
    deer_left: 'assets/characters/directions/deer_left.png',
    deer_side: 'assets/characters/directions/deer_side.png',
    display: 'assets/furniture/pastry_display.png',
    dog: 'assets/characters/current/dog.png',
    dog_back: 'assets/characters/directions/dog_back.png',
    dog_front: 'assets/characters/directions/dog_front.png',
    dog_left: 'assets/characters/directions/dog_left.png',
    dog_side: 'assets/characters/directions/dog_side.png',
    elephant: 'assets/characters/current/elephant.png',
    elephant_back: 'assets/characters/directions/elephant_back.png',
    elephant_front: 'assets/characters/directions/elephant_front.png',
    elephant_left: 'assets/characters/directions/elephant_left.png',
    elephant_side: 'assets/characters/directions/elephant_side.png',
    frog: 'assets/characters/current/frog.png',
    frog_back: 'assets/characters/directions/frog_back.png',
    frog_front: 'assets/characters/directions/frog_front.png',
    frog_left: 'assets/characters/directions/frog_left.png',
    frog_side: 'assets/characters/directions/frog_side.png',
    furniture_bookcase: 'assets/furniture/bookcase.png',
    furniture_cafe_table: 'assets/furniture/cafe_table.png',
    furniture_citrus_tree: 'assets/furniture/citrus_tree.png',
    furniture_ingredient_bowl: 'assets/furniture/ingredient_bowl.png',
    furniture_mixing_bowl: 'assets/furniture/mixing_bowl.png',
    furniture_open_sign: 'assets/furniture/open_sign.png',
    furniture_oven: 'assets/furniture/oven.png',
    furniture_pantry: 'assets/furniture/pantry.png',
    furniture_pastry_display: 'assets/furniture/pastry_display.png',
    furniture_plant: 'assets/furniture/plant.png',
    furniture_prep_sink: 'assets/furniture/prep_sink.png',
    furniture_register: 'assets/furniture/register.png',
    furniture_safe: 'assets/furniture/safe.png',
    furniture_shop_desk: 'assets/furniture/shop_desk.png',
    furniture_sink: 'assets/furniture/sink.png',
    furniture_sofa: 'assets/furniture/sofa.png',
    giraffe: 'assets/characters/current/giraffe.png',
    giraffe_back: 'assets/characters/directions/giraffe_back.png',
    giraffe_front: 'assets/characters/directions/giraffe_front.png',
    giraffe_left: 'assets/characters/directions/giraffe_left.png',
    giraffe_side: 'assets/characters/directions/giraffe_side.png',
    hedgehog: 'assets/characters/current/hedgehog.png',
    hedgehog_back: 'assets/characters/directions/hedgehog_back.png',
    hedgehog_front: 'assets/characters/directions/hedgehog_front.png',
    hedgehog_left: 'assets/characters/directions/hedgehog_left.png',
    hedgehog_side: 'assets/characters/directions/hedgehog_side.png',
    ingredientBowl: 'assets/furniture/ingredient_bowl.png',
    leopard: 'assets/characters/current/leopard.png',
    leopard_back: 'assets/characters/directions/leopard_back.png',
    leopard_front: 'assets/characters/directions/leopard_front.png',
    leopard_left: 'assets/characters/directions/leopard_left.png',
    leopard_side: 'assets/characters/directions/leopard_side.png',
    lion: 'assets/characters/current/lion.png',
    lion_back: 'assets/characters/directions/lion_back.png',
    lion_front: 'assets/characters/directions/lion_front.png',
    lion_left: 'assets/characters/directions/lion_left.png',
    lion_side: 'assets/characters/directions/lion_side.png',
    mixingBowl: 'assets/furniture/mixing_bowl.png',
    moose: 'assets/characters/current/moose.png',
    moose_back: 'assets/characters/directions/moose_back.png',
    moose_front: 'assets/characters/directions/moose_front.png',
    moose_left: 'assets/characters/directions/moose_left.png',
    moose_side: 'assets/characters/directions/moose_side.png',
    open_sign: 'assets/furniture/open_sign.png',
    oven: 'assets/furniture/oven.png',
    owl: 'assets/characters/current/owl.png',
    owl_back: 'assets/characters/directions/owl_back.png',
    owl_front: 'assets/characters/directions/owl_front.png',
    owl_left: 'assets/characters/directions/owl_left.png',
    owl_side: 'assets/characters/directions/owl_side.png',
    panda: 'assets/characters/current/panda.png',
    panda_back: 'assets/characters/directions/panda_back.png',
    panda_front: 'assets/characters/directions/panda_front.png',
    panda_left: 'assets/characters/directions/panda_left.png',
    panda_side: 'assets/characters/directions/panda_side.png',
    pantry: 'assets/furniture/pantry.png',
    penguin: 'assets/characters/current/penguin.png',
    penguin_back: 'assets/characters/directions/penguin_back.png',
    penguin_front: 'assets/characters/directions/penguin_front.png',
    penguin_left: 'assets/characters/directions/penguin_left.png',
    penguin_side: 'assets/characters/directions/penguin_side.png',
    pig: 'assets/characters/current/pig.png',
    pig_back: 'assets/characters/directions/pig_back.png',
    pig_front: 'assets/characters/directions/pig_front.png',
    pig_left: 'assets/characters/directions/pig_left.png',
    pig_side: 'assets/characters/directions/pig_side.png',
    plant: 'assets/furniture/plant.png',
    prep_sink: 'assets/furniture/prep_sink.png',
    red_panda: 'assets/characters/current/red_panda.png',
    red_panda_back: 'assets/characters/directions/red_panda_back.png',
    red_panda_front: 'assets/characters/directions/red_panda_front.png',
    red_panda_left: 'assets/characters/directions/red_panda_left.png',
    red_panda_side: 'assets/characters/directions/red_panda_side.png',
    register: 'assets/furniture/register.png',
    safe: 'assets/furniture/safe.png',
    shop: 'assets/furniture/shop_desk.png',
    sink: 'assets/furniture/sink.png',
    sofa: 'assets/furniture/sofa.png',
    squirrel: 'assets/characters/current/squirrel.png',
    squirrel_back: 'assets/characters/directions/squirrel_back.png',
    squirrel_front: 'assets/characters/directions/squirrel_front.png',
    squirrel_left: 'assets/characters/directions/squirrel_left.png',
    squirrel_side: 'assets/characters/directions/squirrel_side.png',
    table: 'assets/furniture/cafe_table.png',
    tiger: 'assets/characters/current/tiger.png',
    tiger_back: 'assets/characters/directions/tiger_back.png',
    tiger_front: 'assets/characters/directions/tiger_front.png',
    tiger_left: 'assets/characters/directions/tiger_left.png',
    tiger_side: 'assets/characters/directions/tiger_side.png',
    toilet: 'assets/furniture/toilet.png',
    furniture_toilet: 'assets/furniture/toilet.png',
  },
  audio: {
    // Chill / coffee-shop / rainy-day playlist (CC0 Holizna + Pro Sensory)
    music: 'assets/audio/music/chill_laundry.mp3',
    music2: 'assets/audio/music/chill_keeping_cool.mp3',
    music3: 'assets/audio/music/chill_windows_down.mp3',
    music4: 'assets/audio/music/chill_2hour_delay.mp3',
    music5: 'assets/audio/music/chill_snow_drift.mp3',
    music6: 'assets/audio/music/chill_first_snow.mp3',
    music7: 'assets/audio/music/chill_happy_song.mp3',
    music8: 'assets/audio/music/bakery_loop.mp3',
    click: 'assets/audio/sfx/click.ogg',
    confirm: 'assets/audio/sfx/confirm.ogg',
    drop: 'assets/audio/sfx/drop.ogg',
    bell: 'assets/audio/sfx/bell.ogg',
    happy: 'assets/audio/sfx/happy.ogg',
    sad: 'assets/audio/sfx/sad.ogg',
  },
};
